name: SimpleScoreboard
version: 2.1
author: yLeoft_
main: me.leonardo.scoreboard.Main
description: SimpleScoreboard plugin!

commands:
  scoreboard:
    aliases: [sb]
    description: Main command of SimpleScoreboard